# Generated by Django 4.1.7 on 2023-05-10 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 52, 39, 956566, tzinfo=datetime.timezone.utc)),
        ),
    ]
