# Generated by Django 4.1.7 on 2023-05-10 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_resettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 14, 14, 3, 983726, tzinfo=datetime.timezone.utc)),
        ),
    ]
