# Generated by Django 4.1.7 on 2023-05-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
