# Generated by Django 4.1.7 on 2023-05-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_participant_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='user_name',
            new_name='user',
        ),
    ]
