# Generated by Django 4.1.7 on 2023-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_rename_user_name_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='has_chat_joined',
            field=models.BooleanField(default=False),
        ),
    ]
